/*
Copyright 2016 Vanderbilt University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/** \file
* Autogenerated public API
*/

#ifndef ACCRE_LIO_AUTHN_ABSTRACT_H_INCLUDED
#define ACCRE_LIO_AUTHN_ABSTRACT_H_INCLUDED

#include <lio/visibility.h>

#ifdef __cplusplus
extern "C" {
#endif

// Typedefs
typedef struct lio_authn_t lio_authn_t;
typedef struct lio_creds_t lio_creds_t;
//! FIXME: leaky
typedef struct lio_authn_fake_priv_t lio_authn_fake_priv_t;

// Functions

#ifdef __cplusplus
}
#endif

#endif /* ^ ACCRE_LIO_AUTHN_ABSTRACT_H_INCLUDED ^ */ 
