/*
Copyright 2016 Vanderbilt University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/** \file
* Autogenerated public API
*/

#ifndef ACCRE_LIO_CACHE_PRIV_H_INCLUDED
#define ACCRE_LIO_CACHE_PRIV_H_INCLUDED

#include <lio/ex3_abstract.h>
#include <lio/ex3_types.h>
#include <lio/lio_visibility.h>

#ifdef __cplusplus
extern "C" {
#endif

// Typedefs
typedef struct cache_cond_t cache_cond_t;
typedef struct cache_counters_t cache_counters_t;
typedef struct cache_fn_t cache_fn_t;
typedef struct cache_page_t cache_page_t;
typedef struct cache_partial_page_t cache_partial_page_t;
typedef struct cache_range_t cache_range_t;
typedef struct cache_segment_t cache_segment_t;
typedef struct cache_t cache_t;
typedef struct data_page_t data_page_t;
typedef struct lio_cache_stats_get_t lio_cache_stats_get_t;
typedef struct page_handle_t page_handle_t;
typedef struct page_table_t page_table_t;

// Functions
LIO_API lio_cache_stats_get_t get_lio_cache_stats_get(cache_t *c);
LIO_API int lio_cache_pages_drop(segment_t *seg, ex_off_t lo, ex_off_t hi);

#ifdef __cplusplus
}
#endif

#endif /* ^ ACCRE_LIO_CACHE_PRIV_H_INCLUDED ^ */ 
