/*
Copyright 2016 Vanderbilt University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/** \file
* Autogenerated public API
*/

#ifndef ACCRE_LIO_EX3_HEADER_H_INCLUDED
#define ACCRE_LIO_EX3_HEADER_H_INCLUDED

#include "lio/lio_visibility.h"
#include <lio/ex3_types.h>
#include <tbx/list.h>

#ifdef __cplusplus
extern "C" {
#endif

// Typedefs
typedef struct ex_header_t ex_header_t;

// Functions

// Exported types. To be obscured
struct ex_header_t {
    char *name;
    ex_id_t id;
    char *type;
    tbx_list_t *attributes;  //should be a key/value pair struct?
};

#ifdef __cplusplus
}
#endif

#endif /* ^ ACCRE_LIO_EX3_HEADER_H_INCLUDED ^ */ 
