/*
Copyright 2016 Vanderbilt University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/** \file
* Autogenerated public API
*/

#ifndef ACCRE_LIO_LIO_FUSE_H_INCLUDED
#define ACCRE_LIO_LIO_FUSE_H_INCLUDED

#ifdef HAS_FUSE3
    #define FUSE_USE_VERSION 30
    #include <fuse3/fuse.h>
#else
    #define FUSE_USE_VERSION 26
    #include <fuse.h>
#endif

#include <lio/visibility.h>

#ifdef __cplusplus
extern "C" {
#endif

// Typedefs
typedef struct lio_fuse_file_handle_s lio_fuse_file_handle_t;
typedef struct lio_fuse_init_args_t lio_fuse_init_args_t;
typedef struct lio_fuse_t lio_fuse_t;

// Functions

// Global constants
LIO_API extern struct fuse_operations lfs_fops;

// Exported types. To be obscured
struct lio_fuse_init_args_t {
    lio_config_t *lc;
    char *mount_point;
    int lio_argc;
    char **lio_argv;
};

#ifdef __cplusplus
}
#endif

#endif /* ^ ACCRE_LIO_LIO_FUSE_H_INCLUDED ^ */ 
