/*
Copyright 2016 Vanderbilt University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/** \file
* Autogenerated public API
*/

#ifndef ACCRE_LIO_RS_SIMPLE_PRIV_H_INCLUDED
#define ACCRE_LIO_RS_SIMPLE_PRIV_H_INCLUDED

#include "lio/lio_visibility.h"

#ifdef __cplusplus
extern "C" {
#endif

// Typedefs
typedef struct rs_simple_priv_t rs_simple_priv_t;
typedef struct rss_check_entry_t rss_check_entry_t;
typedef struct rss_rid_entry_t rss_rid_entry_t;

// Functions

#ifdef __cplusplus
}
#endif

#endif /* ^ ACCRE_LIO_RS_SIMPLE_PRIV_H_INCLUDED ^ */ 