/*
Copyright 2016 Vanderbilt University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/** \file
* Autogenerated public API
*/

#ifndef ACCRE_LIO_SEGMENT_CACHE_H_INCLUDED
#define ACCRE_LIO_SEGMENT_CACHE_H_INCLUDED

#include <lio/lio_visibility.h>

#ifdef __cplusplus
extern "C" {
#endif

// Typedefs

// Functions
LIO_API int lio_cache_stats_get(cache_t *c, lio_cache_stats_get_t *cs);
LIO_API int lio_cache_stats_get_print(lio_cache_stats_get_t *cs, char *buffer, int *used, int nmax);
LIO_API lio_cache_stats_get_t segment_lio_cache_stats_get(segment_t *seg);

#ifdef __cplusplus
}
#endif

#endif /* ^ ACCRE_LIO_SEGMENT_CACHE_H_INCLUDED ^ */ 
