/*
Copyright 2016 Vanderbilt University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/** \file
* Autogenerated public API
*/

#ifndef ACCRE_LIO_TRACE_H_INCLUDED
#define ACCRE_LIO_TRACE_H_INCLUDED

#include "lio/lio_visibility.h"

#ifdef __cplusplus
extern "C" {
#endif

// Typedefs
typedef struct trace_file_t trace_file_t;
typedef struct trace_op_t trace_op_t;
typedef struct trace_stats_t trace_stats_t;
typedef struct trace_t trace_t;

// Functions

#ifdef __cplusplus
}
#endif

#endif /* ^ ACCRE_LIO_TRACE_H_INCLUDED ^ */ 