Document: lstore
Title: Debian lstore Manual
Author: <insert document author here>
Abstract: This manual describes what lstore is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lstore/lstore.sgml.gz

Format: postscript
Files: /usr/share/doc/lstore/lstore.ps.gz

Format: text
Files: /usr/share/doc/lstore/lstore.text.gz

Format: HTML
Index: /usr/share/doc/lstore/html/index.html
Files: /usr/share/doc/lstore/html/*.html
