/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_rsz_5frequest_2eproto__INCLUDED
#define PROTOBUF_C_rsz_5frequest_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "rsz_req.pb-c.h"
#include "rsz_cap.pb-c.h"

typedef struct _Rs__Zmq__RszRequest Rs__Zmq__RszRequest;
typedef struct _Rs__Zmq__RszRequest__RszDataAttr Rs__Zmq__RszRequest__RszDataAttr;
typedef struct _Rs__Zmq__RszRequest__RszHints Rs__Zmq__RszRequest__RszHints;


/* --- enums --- */


/* --- messages --- */

struct  _Rs__Zmq__RszRequest__RszDataAttr
{
  ProtobufCMessage base;
  int64_t duration;
  int64_t reliability;
  int64_t type;
};
#define RS__ZMQ__RSZ_REQUEST__RSZ_DATA_ATTR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rs__zmq__rsz_request__rsz_data_attr__descriptor) \
    , 0, 0, 0 }


struct  _Rs__Zmq__RszRequest__RszHints
{
  ProtobufCMessage base;
  char *fixed_rid_key;
  char *local_rsq;
  int32_t status;
};
#define RS__ZMQ__RSZ_REQUEST__RSZ_HINTS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rs__zmq__rsz_request__rsz_hints__descriptor) \
    , NULL, NULL, 0 }


struct  _Rs__Zmq__RszRequest
{
  ProtobufCMessage base;
  char *rs_query;
  int32_t request_size;
  int32_t num_rid;
  int32_t timeout;
  Rs__Zmq__RszRequest__RszDataAttr *data_attr;
  size_t n_hints;
  Rs__Zmq__RszRequest__RszHints **hints;
  size_t n_cap;
  Rs__Zmq__RszCapSet **cap;
  size_t n_req;
  Rs__Zmq__RszReqSet **req;
  int32_t fixed_size;
};
#define RS__ZMQ__RSZ_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rs__zmq__rsz_request__descriptor) \
    , NULL, 0, 0, 0, NULL, 0,NULL, 0,NULL, 0,NULL, 0 }


/* Rs__Zmq__RszRequest__RszDataAttr methods */
void   rs__zmq__rsz_request__rsz_data_attr__init
                     (Rs__Zmq__RszRequest__RszDataAttr         *message);
/* Rs__Zmq__RszRequest__RszHints methods */
void   rs__zmq__rsz_request__rsz_hints__init
                     (Rs__Zmq__RszRequest__RszHints         *message);
/* Rs__Zmq__RszRequest methods */
void   rs__zmq__rsz_request__init
                     (Rs__Zmq__RszRequest         *message);
size_t rs__zmq__rsz_request__get_packed_size
                     (const Rs__Zmq__RszRequest   *message);
size_t rs__zmq__rsz_request__pack
                     (const Rs__Zmq__RszRequest   *message,
                      uint8_t             *out);
size_t rs__zmq__rsz_request__pack_to_buffer
                     (const Rs__Zmq__RszRequest   *message,
                      ProtobufCBuffer     *buffer);
Rs__Zmq__RszRequest *
       rs__zmq__rsz_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rs__zmq__rsz_request__free_unpacked
                     (Rs__Zmq__RszRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Rs__Zmq__RszRequest__RszDataAttr_Closure)
                 (const Rs__Zmq__RszRequest__RszDataAttr *message,
                  void *closure_data);
typedef void (*Rs__Zmq__RszRequest__RszHints_Closure)
                 (const Rs__Zmq__RszRequest__RszHints *message,
                  void *closure_data);
typedef void (*Rs__Zmq__RszRequest_Closure)
                 (const Rs__Zmq__RszRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor rs__zmq__rsz_request__descriptor;
extern const ProtobufCMessageDescriptor rs__zmq__rsz_request__rsz_data_attr__descriptor;
extern const ProtobufCMessageDescriptor rs__zmq__rsz_request__rsz_hints__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_rsz_5frequest_2eproto__INCLUDED */
