/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_rsz_5freq_2eproto__INCLUDED
#define PROTOBUF_C_rsz_5freq_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Rs__Zmq__RszReqSet Rs__Zmq__RszReqSet;


/* --- enums --- */


/* --- messages --- */

struct  _Rs__Zmq__RszReqSet
{
  ProtobufCMessage base;
  int32_t rid_index;
  int32_t size;
  char *rid_key;
};
#define RS__ZMQ__RSZ_REQ_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rs__zmq__rsz_req_set__descriptor) \
    , 0, 0, NULL }


/* Rs__Zmq__RszReqSet methods */
void   rs__zmq__rsz_req_set__init
                     (Rs__Zmq__RszReqSet         *message);
size_t rs__zmq__rsz_req_set__get_packed_size
                     (const Rs__Zmq__RszReqSet   *message);
size_t rs__zmq__rsz_req_set__pack
                     (const Rs__Zmq__RszReqSet   *message,
                      uint8_t             *out);
size_t rs__zmq__rsz_req_set__pack_to_buffer
                     (const Rs__Zmq__RszReqSet   *message,
                      ProtobufCBuffer     *buffer);
Rs__Zmq__RszReqSet *
       rs__zmq__rsz_req_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rs__zmq__rsz_req_set__free_unpacked
                     (Rs__Zmq__RszReqSet *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Rs__Zmq__RszReqSet_Closure)
                 (const Rs__Zmq__RszReqSet *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor rs__zmq__rsz_req_set__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_rsz_5freq_2eproto__INCLUDED */
