/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "rsz_req.pb-c.h"
void   rs__zmq__rsz_req_set__init
                     (Rs__Zmq__RszReqSet         *message)
{
  static Rs__Zmq__RszReqSet init_value = RS__ZMQ__RSZ_REQ_SET__INIT;
  *message = init_value;
}
size_t rs__zmq__rsz_req_set__get_packed_size
                     (const Rs__Zmq__RszReqSet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_req_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rs__zmq__rsz_req_set__pack
                     (const Rs__Zmq__RszReqSet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_req_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rs__zmq__rsz_req_set__pack_to_buffer
                     (const Rs__Zmq__RszReqSet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_req_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rs__Zmq__RszReqSet *
       rs__zmq__rsz_req_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rs__Zmq__RszReqSet *)
     protobuf_c_message_unpack (&rs__zmq__rsz_req_set__descriptor,
                                allocator, len, data);
}
void   rs__zmq__rsz_req_set__free_unpacked
                     (Rs__Zmq__RszReqSet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_req_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rs__zmq__rsz_req_set__field_descriptors[3] =
{
  {
    "rid_index",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszReqSet, rid_index),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszReqSet, size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rid_key",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszReqSet, rid_key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rs__zmq__rsz_req_set__field_indices_by_name[] = {
  0,   /* field[0] = rid_index */
  2,   /* field[2] = rid_key */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange rs__zmq__rsz_req_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rs__zmq__rsz_req_set__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rs.zmq.RszReqSet",
  "RszReqSet",
  "Rs__Zmq__RszReqSet",
  "rs.zmq",
  sizeof(Rs__Zmq__RszReqSet),
  3,
  rs__zmq__rsz_req_set__field_descriptors,
  rs__zmq__rsz_req_set__field_indices_by_name,
  1,  rs__zmq__rsz_req_set__number_ranges,
  (ProtobufCMessageInit) rs__zmq__rsz_req_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
