/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "rsz_rid_key_value.pb-c.h"
void   rs__zmq__rsz_rid_key__init
                     (Rs__Zmq__RszRidKey         *message)
{
  static Rs__Zmq__RszRidKey init_value = RS__ZMQ__RSZ_RID_KEY__INIT;
  *message = init_value;
}
size_t rs__zmq__rsz_rid_key__get_packed_size
                     (const Rs__Zmq__RszRidKey *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_rid_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rs__zmq__rsz_rid_key__pack
                     (const Rs__Zmq__RszRidKey *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_rid_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rs__zmq__rsz_rid_key__pack_to_buffer
                     (const Rs__Zmq__RszRidKey *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_rid_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rs__Zmq__RszRidKey *
       rs__zmq__rsz_rid_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rs__Zmq__RszRidKey *)
     protobuf_c_message_unpack (&rs__zmq__rsz_rid_key__descriptor,
                                allocator, len, data);
}
void   rs__zmq__rsz_rid_key__free_unpacked
                     (Rs__Zmq__RszRidKey *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_rid_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rs__zmq__rsz_rid_value__init
                     (Rs__Zmq__RszRidValue         *message)
{
  static Rs__Zmq__RszRidValue init_value = RS__ZMQ__RSZ_RID_VALUE__INIT;
  *message = init_value;
}
size_t rs__zmq__rsz_rid_value__get_packed_size
                     (const Rs__Zmq__RszRidValue *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_rid_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rs__zmq__rsz_rid_value__pack
                     (const Rs__Zmq__RszRidValue *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_rid_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rs__zmq__rsz_rid_value__pack_to_buffer
                     (const Rs__Zmq__RszRidValue *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_rid_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rs__Zmq__RszRidValue *
       rs__zmq__rsz_rid_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rs__Zmq__RszRidValue *)
     protobuf_c_message_unpack (&rs__zmq__rsz_rid_value__descriptor,
                                allocator, len, data);
}
void   rs__zmq__rsz_rid_value__free_unpacked
                     (Rs__Zmq__RszRidValue *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_rid_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rs__zmq__rsz_rid_key__field_descriptors[2] =
{
  {
    "rid_key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRidKey, rid_key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRidKey, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rs__zmq__rsz_rid_key__field_indices_by_name[] = {
  1,   /* field[1] = key */
  0,   /* field[0] = rid_key */
};
static const ProtobufCIntRange rs__zmq__rsz_rid_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rs__zmq__rsz_rid_key__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rs.zmq.RszRidKey",
  "RszRidKey",
  "Rs__Zmq__RszRidKey",
  "rs.zmq",
  sizeof(Rs__Zmq__RszRidKey),
  2,
  rs__zmq__rsz_rid_key__field_descriptors,
  rs__zmq__rsz_rid_key__field_indices_by_name,
  1,  rs__zmq__rsz_rid_key__number_ranges,
  (ProtobufCMessageInit) rs__zmq__rsz_rid_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rs__zmq__rsz_rid_value__field_descriptors[1] =
{
  {
    "rid_value",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRidValue, rid_value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rs__zmq__rsz_rid_value__field_indices_by_name[] = {
  0,   /* field[0] = rid_value */
};
static const ProtobufCIntRange rs__zmq__rsz_rid_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rs__zmq__rsz_rid_value__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rs.zmq.RszRidValue",
  "RszRidValue",
  "Rs__Zmq__RszRidValue",
  "rs.zmq",
  sizeof(Rs__Zmq__RszRidValue),
  1,
  rs__zmq__rsz_rid_value__field_descriptors,
  rs__zmq__rsz_rid_value__field_indices_by_name,
  1,  rs__zmq__rsz_rid_value__number_ranges,
  (ProtobufCMessageInit) rs__zmq__rsz_rid_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
