/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_rsz_5frid_5fkey_5fvalue_2eproto__INCLUDED
#define PROTOBUF_C_rsz_5frid_5fkey_5fvalue_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Rs__Zmq__RszRidKey Rs__Zmq__RszRidKey;
typedef struct _Rs__Zmq__RszRidValue Rs__Zmq__RszRidValue;


/* --- enums --- */


/* --- messages --- */

struct  _Rs__Zmq__RszRidKey
{
  ProtobufCMessage base;
  char *rid_key;
  char *key;
};
#define RS__ZMQ__RSZ_RID_KEY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rs__zmq__rsz_rid_key__descriptor) \
    , NULL, NULL }


struct  _Rs__Zmq__RszRidValue
{
  ProtobufCMessage base;
  char *rid_value;
};
#define RS__ZMQ__RSZ_RID_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rs__zmq__rsz_rid_value__descriptor) \
    , NULL }


/* Rs__Zmq__RszRidKey methods */
void   rs__zmq__rsz_rid_key__init
                     (Rs__Zmq__RszRidKey         *message);
size_t rs__zmq__rsz_rid_key__get_packed_size
                     (const Rs__Zmq__RszRidKey   *message);
size_t rs__zmq__rsz_rid_key__pack
                     (const Rs__Zmq__RszRidKey   *message,
                      uint8_t             *out);
size_t rs__zmq__rsz_rid_key__pack_to_buffer
                     (const Rs__Zmq__RszRidKey   *message,
                      ProtobufCBuffer     *buffer);
Rs__Zmq__RszRidKey *
       rs__zmq__rsz_rid_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rs__zmq__rsz_rid_key__free_unpacked
                     (Rs__Zmq__RszRidKey *message,
                      ProtobufCAllocator *allocator);
/* Rs__Zmq__RszRidValue methods */
void   rs__zmq__rsz_rid_value__init
                     (Rs__Zmq__RszRidValue         *message);
size_t rs__zmq__rsz_rid_value__get_packed_size
                     (const Rs__Zmq__RszRidValue   *message);
size_t rs__zmq__rsz_rid_value__pack
                     (const Rs__Zmq__RszRidValue   *message,
                      uint8_t             *out);
size_t rs__zmq__rsz_rid_value__pack_to_buffer
                     (const Rs__Zmq__RszRidValue   *message,
                      ProtobufCBuffer     *buffer);
Rs__Zmq__RszRidValue *
       rs__zmq__rsz_rid_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rs__zmq__rsz_rid_value__free_unpacked
                     (Rs__Zmq__RszRidValue *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Rs__Zmq__RszRidKey_Closure)
                 (const Rs__Zmq__RszRidKey *message,
                  void *closure_data);
typedef void (*Rs__Zmq__RszRidValue_Closure)
                 (const Rs__Zmq__RszRidValue *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor rs__zmq__rsz_rid_key__descriptor;
extern const ProtobufCMessageDescriptor rs__zmq__rsz_rid_value__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_rsz_5frid_5fkey_5fvalue_2eproto__INCLUDED */
