/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_rsz_5fcap_2eproto__INCLUDED
#define PROTOBUF_C_rsz_5fcap_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Rs__Zmq__RszCapSet Rs__Zmq__RszCapSet;


/* --- enums --- */


/* --- messages --- */

struct  _Rs__Zmq__RszCapSet
{
  ProtobufCMessage base;
  char *read;
  char *write;
  char *manage;
};
#define RS__ZMQ__RSZ_CAP_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rs__zmq__rsz_cap_set__descriptor) \
    , NULL, NULL, NULL }


/* Rs__Zmq__RszCapSet methods */
void   rs__zmq__rsz_cap_set__init
                     (Rs__Zmq__RszCapSet         *message);
size_t rs__zmq__rsz_cap_set__get_packed_size
                     (const Rs__Zmq__RszCapSet   *message);
size_t rs__zmq__rsz_cap_set__pack
                     (const Rs__Zmq__RszCapSet   *message,
                      uint8_t             *out);
size_t rs__zmq__rsz_cap_set__pack_to_buffer
                     (const Rs__Zmq__RszCapSet   *message,
                      ProtobufCBuffer     *buffer);
Rs__Zmq__RszCapSet *
       rs__zmq__rsz_cap_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rs__zmq__rsz_cap_set__free_unpacked
                     (Rs__Zmq__RszCapSet *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Rs__Zmq__RszCapSet_Closure)
                 (const Rs__Zmq__RszCapSet *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor rs__zmq__rsz_cap_set__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_rsz_5fcap_2eproto__INCLUDED */
