/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "rsz_request.pb-c.h"
void   rs__zmq__rsz_request__rsz_data_attr__init
                     (Rs__Zmq__RszRequest__RszDataAttr         *message)
{
  static Rs__Zmq__RszRequest__RszDataAttr init_value = RS__ZMQ__RSZ_REQUEST__RSZ_DATA_ATTR__INIT;
  *message = init_value;
}
void   rs__zmq__rsz_request__rsz_hints__init
                     (Rs__Zmq__RszRequest__RszHints         *message)
{
  static Rs__Zmq__RszRequest__RszHints init_value = RS__ZMQ__RSZ_REQUEST__RSZ_HINTS__INIT;
  *message = init_value;
}
void   rs__zmq__rsz_request__init
                     (Rs__Zmq__RszRequest         *message)
{
  static Rs__Zmq__RszRequest init_value = RS__ZMQ__RSZ_REQUEST__INIT;
  *message = init_value;
}
size_t rs__zmq__rsz_request__get_packed_size
                     (const Rs__Zmq__RszRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rs__zmq__rsz_request__pack
                     (const Rs__Zmq__RszRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rs__zmq__rsz_request__pack_to_buffer
                     (const Rs__Zmq__RszRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rs__Zmq__RszRequest *
       rs__zmq__rsz_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rs__Zmq__RszRequest *)
     protobuf_c_message_unpack (&rs__zmq__rsz_request__descriptor,
                                allocator, len, data);
}
void   rs__zmq__rsz_request__free_unpacked
                     (Rs__Zmq__RszRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rs__zmq__rsz_request__rsz_data_attr__field_descriptors[3] =
{
  {
    "duration",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest__RszDataAttr, duration),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reliability",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest__RszDataAttr, reliability),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest__RszDataAttr, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rs__zmq__rsz_request__rsz_data_attr__field_indices_by_name[] = {
  0,   /* field[0] = duration */
  1,   /* field[1] = reliability */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange rs__zmq__rsz_request__rsz_data_attr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rs__zmq__rsz_request__rsz_data_attr__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rs.zmq.RszRequest.RszDataAttr",
  "RszDataAttr",
  "Rs__Zmq__RszRequest__RszDataAttr",
  "rs.zmq",
  sizeof(Rs__Zmq__RszRequest__RszDataAttr),
  3,
  rs__zmq__rsz_request__rsz_data_attr__field_descriptors,
  rs__zmq__rsz_request__rsz_data_attr__field_indices_by_name,
  1,  rs__zmq__rsz_request__rsz_data_attr__number_ranges,
  (ProtobufCMessageInit) rs__zmq__rsz_request__rsz_data_attr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rs__zmq__rsz_request__rsz_hints__field_descriptors[3] =
{
  {
    "fixed_rid_key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest__RszHints, fixed_rid_key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_rsq",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest__RszHints, local_rsq),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest__RszHints, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rs__zmq__rsz_request__rsz_hints__field_indices_by_name[] = {
  0,   /* field[0] = fixed_rid_key */
  1,   /* field[1] = local_rsq */
  2,   /* field[2] = status */
};
static const ProtobufCIntRange rs__zmq__rsz_request__rsz_hints__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rs__zmq__rsz_request__rsz_hints__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rs.zmq.RszRequest.RszHints",
  "RszHints",
  "Rs__Zmq__RszRequest__RszHints",
  "rs.zmq",
  sizeof(Rs__Zmq__RszRequest__RszHints),
  3,
  rs__zmq__rsz_request__rsz_hints__field_descriptors,
  rs__zmq__rsz_request__rsz_hints__field_indices_by_name,
  1,  rs__zmq__rsz_request__rsz_hints__number_ranges,
  (ProtobufCMessageInit) rs__zmq__rsz_request__rsz_hints__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rs__zmq__rsz_request__field_descriptors[9] =
{
  {
    "rs_query",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest, rs_query),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest, request_size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_rid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest, num_rid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest, timeout),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_attr",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest, data_attr),
    &rs__zmq__rsz_request__rsz_data_attr__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hints",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest, n_hints),
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest, hints),
    &rs__zmq__rsz_request__rsz_hints__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cap",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest, n_cap),
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest, cap),
    &rs__zmq__rsz_cap_set__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest, n_req),
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest, req),
    &rs__zmq__rsz_req_set__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fixed_size",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszRequest, fixed_size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rs__zmq__rsz_request__field_indices_by_name[] = {
  6,   /* field[6] = cap */
  4,   /* field[4] = data_attr */
  8,   /* field[8] = fixed_size */
  5,   /* field[5] = hints */
  2,   /* field[2] = num_rid */
  7,   /* field[7] = req */
  1,   /* field[1] = request_size */
  0,   /* field[0] = rs_query */
  3,   /* field[3] = timeout */
};
static const ProtobufCIntRange rs__zmq__rsz_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor rs__zmq__rsz_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rs.zmq.RszRequest",
  "RszRequest",
  "Rs__Zmq__RszRequest",
  "rs.zmq",
  sizeof(Rs__Zmq__RszRequest),
  9,
  rs__zmq__rsz_request__field_descriptors,
  rs__zmq__rsz_request__field_indices_by_name,
  1,  rs__zmq__rsz_request__number_ranges,
  (ProtobufCMessageInit) rs__zmq__rsz_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
