/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "rsz_response.pb-c.h"
void   rs__zmq__rsz_response__init
                     (Rs__Zmq__RszResponse         *message)
{
  static Rs__Zmq__RszResponse init_value = RS__ZMQ__RSZ_RESPONSE__INIT;
  *message = init_value;
}
size_t rs__zmq__rsz_response__get_packed_size
                     (const Rs__Zmq__RszResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rs__zmq__rsz_response__pack
                     (const Rs__Zmq__RszResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rs__zmq__rsz_response__pack_to_buffer
                     (const Rs__Zmq__RszResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rs__Zmq__RszResponse *
       rs__zmq__rsz_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rs__Zmq__RszResponse *)
     protobuf_c_message_unpack (&rs__zmq__rsz_response__descriptor,
                                allocator, len, data);
}
void   rs__zmq__rsz_response__free_unpacked
                     (Rs__Zmq__RszResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rs__zmq__rsz_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rs__zmq__rsz_response__field_descriptors[2] =
{
  {
    "cap",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszResponse, n_cap),
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszResponse, cap),
    &rs__zmq__rsz_cap_set__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszResponse, n_req),
    PROTOBUF_C_OFFSETOF(Rs__Zmq__RszResponse, req),
    &rs__zmq__rsz_req_set__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rs__zmq__rsz_response__field_indices_by_name[] = {
  0,   /* field[0] = cap */
  1,   /* field[1] = req */
};
static const ProtobufCIntRange rs__zmq__rsz_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rs__zmq__rsz_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rs.zmq.RszResponse",
  "RszResponse",
  "Rs__Zmq__RszResponse",
  "rs.zmq",
  sizeof(Rs__Zmq__RszResponse),
  2,
  rs__zmq__rsz_response__field_descriptors,
  rs__zmq__rsz_response__field_indices_by_name,
  1,  rs__zmq__rsz_response__number_ranges,
  (ProtobufCMessageInit) rs__zmq__rsz_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
