/*
Copyright 2016 Vanderbilt University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/** \file
* Autogenerated public API
*/

#ifndef ACCRE_GOP_CALLBACK_H_INCLUDED
#define ACCRE_GOP_CALLBACK_H_INCLUDED

#include <gop/gop_visibility.h>

#ifdef __cplusplus
extern "C" {
#endif

// Typedefs
typedef struct callback_t callback_t;

// Functions
GOP_API void gop_cb_set(callback_t *cb, void (*fn)(void *priv, int value), void *priv);

// Exported types. To be obscured.
struct callback_t {   //** Used for application level callback
    void *priv;
    void (*fn)(void *priv, int value);
    callback_t *next;
    callback_t *tail;
};

#ifdef __cplusplus
}
#endif

#endif /* ^ ACCRE_GOP_CALLBACK_H_INCLUDED ^ */ 
