/*
Copyright 2016 Vanderbilt University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/** \file
* Autogenerated public API
*/

#ifndef ACCRE_GOP_MQ_STREAM_H_INCLUDED
#define ACCRE_GOP_MQ_STREAM_H_INCLUDED

#include <gop/gop_visibility.h>
#include <gop/mq_ongoing.h>

#ifdef __cplusplus
extern "C" {
#endif

// Typedefs
typedef struct mq_stream_t mq_stream_t;

// Functions
GOP_API mq_stream_t *gop_gop_mq_stream_read_create(mq_context_t *mqc,  mq_ongoing_t *ongoing, char *host_id, int hid_len, mq_frame_t *fdata, mq_msg_t *remote_host, int to);
GOP_API int64_t gop_gop_mq_stream_read_varint(mq_stream_t *mqs, int *error);
GOP_API mq_stream_t *gop_gop_mq_stream_write_create(mq_context_t *mqc, mq_portal_t *server_portal, mq_ongoing_t *ongoing, char tbx_pack_type, int max_size, int timeout, mq_msg_t *address, mq_frame_t *fid, mq_frame_t *hid, int launch_flusher);
GOP_API int gop_gop_mq_stream_write_varint(mq_stream_t *mqs, int64_t value);
GOP_API void gop_mq_stream_destroy(mq_stream_t *mqs);
GOP_API int gop_mq_stream_read(mq_stream_t *mqs, void *buffer, int nbytes);
GOP_API int gop_mq_stream_write(mq_stream_t *mqs, void *buffer, int nbytes);
GOP_API void gop_mqs_server_more_cb(void *arg, mq_task_t *task);

// Preprocessor constants
#define MQS_PACK_RAW 'R'
#define MQS_PACK_COMPRESS 'Z'

// FIXME don't open-code this
#define MQS_MORE_DATA_KEY  "mqs_more"
#define MQS_MORE_DATA_SIZE 8



#ifdef __cplusplus
}
#endif

#endif /* ^ ACCRE_GOP_MQ_STREAM_H_INCLUDED ^ */ 
