/*
Copyright 2016 Vanderbilt University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/** \file
* Autogenerated public API
*/

#ifndef ACCRE_GOP_TYPES_H_INCLUDED
#define ACCRE_GOP_TYPES_H_INCLUDED

#include <gop/visibility.h>

#ifdef __cplusplus
extern "C" {
#endif

// Typedefs
typedef struct command_op_t command_op_t;
typedef struct gop_control_t gop_control_t;
typedef struct op_common_t op_common_t;
typedef struct op_data_t op_data_t;
typedef struct op_generic_t op_generic_t;
typedef struct op_status_t op_status_t;
typedef struct opque_t opque_t;
typedef struct portal_context_t portal_context_t;
typedef struct portal_fn_t portal_fn_t;
typedef struct que_data_t que_data_t;

// Functions

#ifdef __cplusplus
}
#endif

#endif /* ^ ACCRE_GOP_TYPES_H_INCLUDED ^ */ 
