#!/bin/bash

set -eu 
ABSOLUTE_PATH=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
source $ABSOLUTE_PATH/functions.sh

find $LSTORE_RELEASE_BASE/src -name *.h | xargs grep -e '^..._API' -h | \
    sed 's,\(..._API\) .* \(.*\)(.*,\1 \2,' | \
    sed 's,\*,,' | sort > function_api.txt

rm -f enum_api.txt struct_api.txt fn_pointer_api.txt typedef_api.txt leaky_api.txt
touch enum_api.txt struct_api.txt fn_pointer_api.txt typedef_api.txt leaky_api.txt

for DIR in toolbox/tbx gop/gop ibp/ibp lio/lio; do
    ls $LSTORE_RELEASE_BASE/src/$DIR/*.h | xargs grep -h 'typedef' | \
        sed -n 's,.*typedef enum,typedef enum,p' >> enum_api.txt

    ls $LSTORE_RELEASE_BASE/src/$DIR/*.h | xargs grep -h 'typedef' | \
        sed -n 's,.*typedef struct,typedef struct,p' >> struct_api.txt

    ls $LSTORE_RELEASE_BASE/src/$DIR/*.h | xargs grep -h 'typedef' | \
        sed -n 's,.*typedef \(.*(\*.*)(.*)\);,typedef \1;,p' >> fn_pointer_api.txt

    ls $LSTORE_RELEASE_BASE/src/$DIR/*.h | xargs grep -h 'typedef' | \
        sed -n 's,.*typedef,typedef,p' >> typedef_api.txt

    ls $LSTORE_RELEASE_BASE/src/$DIR/*.h | xargs grep -h 'struct' | \
        sed -n 's,^ *struct \(.*\) {.*,\1,p' >> leaky_api.txt
done

# typedef ex_off_t (*lio_segment_size_fn_t)(segment_t *seg);
comm -13 <(sort struct_api.txt) <(sort typedef_api.txt) > nostruct_api.txt
comm -13 <(sort enum_api.txt) <(sort nostruct_api.txt) > missing1_api.txt
comm -13 <(sort fn_pointer_api.txt) <(sort missing1_api.txt) > missing2_api.txt

# Autogenerate an RST with the whole API
cat << EOF > $LSTORE_RELEASE_BASE/doc/api-autogen.rst
.. DO NOT EDIT Autogenerated by scripts/dump-api.sh

Current LStore API
==================

This document lists the exported LStore API.

.. toctree::

Functions
---------
$(sed 's,^.*_API,* ,' function_api.txt)

Opaque Structs
--------------

$(sed 's,^,* ,' struct_api.txt)


Non-Opaque Structs
------------------
Do *NOT* allocate these on the stack. They will be hidden at some point soon.

$(sed 's,^,* ,' leaky_api.txt)


Enumerations
------------

$(sed 's,^,* ,' enum_api.txt)


Function Pointer Types
----------------------
Since so many functions accept function pointers, we typedef'd them all to
clean up the argument lists.

$(sed 's,^,* ,' fn_pointer_api.txt)


Other exports
-------------

$(sed 's,^,* ,' missing2_api.txt)


EOF
