//*** Do not edit ****
//*** Automatically generated by cmake ***
 
const char *vstr = "\n"
             "CMake Build Date: Thu Oct 20 16:29:48 CDT 2016\n"
             "Compiler: cc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609\n"
             "Compile Flags(Debug):  -std=c99 -D_REENTRANT -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fvisibility=hidden -fno-strict-aliasing -Wall -Wextra -Werror -Wno-unused-parameter -Wno-deprecated-declarations -Wno-error=sign-compare  -g \n"
             "Build Host: dev-depot1.accre.vanderbilt.edu\n"
             "Build OS: Linux-4.4.0-31-generic-x86_64\n";        

const char *server_version() {
    return(vstr);
}

   

